WITH

MAINTABLE AS 
(
	SELECT TBLRESPONSIBILITIES.SUPPLIER AS SUPPLIER_NUMBER, SUPPLIER_ALIGNMENT.SUPPLIERNAME AS SUPPLIER_NAME, TBLCONTACT.[FIRST], 
	TBLCONTACT.[LAST], TBLCONTACT.MOBILE, TBLCONTACT.EMAIL AS SUPPLIER_EMAIL, SPA_ALIGNMENT.NOVELL AS SPA_ID, SPA_ALIGNMENT.SPA AS SPA_NAME, 
	TBLRESPONSIBILITIES.ROLE, SPA_ALIGNMENT.EMAIL AS SPA_EMAIL, SPA_ALIGNMENT.TITLE AS SPA_TITLE   

	FROM ITEMMANAGEMENT.DBO.TBLCONTACT 
	INNER JOIN ITEMMANAGEMENT.DBO.TBLRESPONSIBILITIES
	ON TBLCONTACT.CONTACTID = TBLRESPONSIBILITIES.CONTACTID
	INNER JOIN ITEMMANAGEMENT.DBO.SUPPLIER_ALIGNMENT 
	ON TBLRESPONSIBILITIES.SUPPLIER = SUPPLIER_ALIGNMENT.SUPPLIERNUMBER
	INNER JOIN ITEMMANAGEMENT.DBO.SPA_ALIGNMENT 
	ON SUPPLIER_ALIGNMENT.SUPPLIERGROUP = SPA_ALIGNMENT.SUPPLIERGROUP

	WHERE TBLRESPONSIBILITIES.SUPPLIER IS NOT NULL
	AND SUPPLIER_ALIGNMENT.SUPPLIERNAME IS NOT NULL
	AND TBLCONTACT.EMAIL IS NOT NULL
	AND SPA_ALIGNMENT.SPA IS NOT NULL
	AND SPA_ALIGNMENT.EMAIL IS NOT NULL
	AND SPA_ALIGNMENT.TITLE IS NOT NULL
),

HAS_ROLE AS
(
	SELECT SUPPLIER_NUMBER, SUPPLIER_NAME, [ROLE], SUPPLIER_EMAIL, SPA_ID, SPA_NAME, 
	SPA_TITLE, SPA_EMAIL, 'HAS_ROLE' AS ROLE_FLAG 
	
	FROM MAINTABLE
	WHERE [ROLE] IN ('ROLE_PLACEHOLDER')
),

NO_ROLE AS 
(
	SELECT SUPPLIER_NUMBER, SUPPLIER_NAME, [ROLE], SUPPLIER_EMAIL, SPA_ID, SPA_NAME, 
	SPA_TITLE, SPA_EMAIL, 'NO_ROLE' AS ROLE_FLAG 
	
	FROM MAINTABLE
	WHERE SUPPLIER_NUMBER NOT IN (SELECT DISTINCT SUPPLIER_NUMBER FROM HAS_ROLE)
)

SELECT * FROM HAS_ROLE 
UNION
SELECT * FROM NO_ROLE